channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - nb_conda
  - pip:
    - alpha-vantage==2.1.3
    - beautifulsoup4==4.8.2
    - pandas==1.0.1
    - numpy==1.18.1
    - slack==0.0.2
    - slackclient==2.5.0
    - slackeventsapi==2.1.0
    - websocket-client==0.57.0